In [144]:
import pandas as pd
df =  pd.read_csv("raw_data2.csv", error_bad_lines=False)
def dfreplace(df, *args, **kwargs):
    s = pd.Series(df.values.flatten())
    s = s.str.replace(*args, **kwargs)
    return pd.DataFrame(s.values.reshape(df.shape), df.index, df.columns)

df = dfreplace(df, ',', '')

In [145]:
df.head()

,"STN,","YYYYMMDD,","DDVEC,","FHVEC,","FG,","FHX,","FHXH,","FHN,","FHNH,","FXX,",...,"VVNH,","VVX,","VVXH,","NG,","UG,","UX,","UXH,","UN,","UNH,",EV24
0,370,20000101,239,21,26,40,3,10,17,70,...,19,38,23,8,99,100,10,98,1,NaN
1,370,20000102,194,35,36,50,11,10,1,90,...,4,59,22,8,98,100,2,95,12,NaN
2,370,20000103,204,63,63,80,19,40,1,120,...,24,68,10,8,92,97,24,89,18,NaN
3,370,20000104,222,53,59,90,17,30,7,170,...,8,75,19,7,93,99,5,77,18,NaN
4,370,20000105,193,37,39,50,13,30,1,80,...,8,80,14,3,92,97,8,82,14,NaN

In [154]:
import re
import numpy as np
for i in df.columns:
    df[i] = df[i].astype(str)
    df[i][df[i].apply(lambda i: True if re.search('^\s*$', str(i)) else False)]=np.NaN

C:\Users\sophi\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [155]:
df['YYYY'] = df['YYYYMMDD,'].str.slice(0,4) #create a variable for years
df['MM'] = df['YYYYMMDD,'].str.slice(4,6)#create a variable for months
df['DD'] = df['YYYYMMDD,'].str.slice(6,8)
for i in df.columns:
        df[i] =df[i].astype(int, errors= 'ignore') 
df = df.drop('YYYYMMDD,', axis=1)

In [156]:
#df['YYYY'] = df['YYYYMMDD,'].dt.year #create a variable for years
#df['MM'] = df['YYYYMMDD,'].dt.month #create a variable for months
#df['DD'] = df['YYYYMMDD,'].dt.day #create a variable for days

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7305 entries, 0 to 7304
Data columns (total 43 columns):
STN,      7305 non-null int32
DDVEC,    7305 non-null object
FHVEC,    7305 non-null object
FG,       7305 non-null object
FHX,      7305 non-null object
FHXH,     7305 non-null object
FHN,      7305 non-null object
FHNH,     7305 non-null object
FXX,      7305 non-null int32
FXXH,     7305 non-null int32
TG,       7305 non-null int32
TN,       7305 non-null int32
TNH,      7305 non-null int32
TX,       7305 non-null int32
TXH,      7305 non-null int32
T10N,     7305 non-null int32
T10NH,    7305 non-null int32
SQ,       7305 non-null int32
SP,       7305 non-null int32
Q,        7305 non-null int32
DR,       7305 non-null int32
RH,       7305 non-null int32
RHX,      7305 non-null int32
RHXH,     7305 non-null int32
PG,       7305 non-null int32
PX,       7305 non-null int32
PXH,      7305 non-null int32
PN,       7305 non-null int32
PNH,      7305 non-null int32
VVN,      7305 non-null object
VVNH,     7305 non-null object
VVX,      7305 non-null object
VVXH,     7305 non-null object
NG,       7305 non-null object
UG,       7305 non-null int32
UX,       7305 non-null int32
UXH,      7305 non-null int32
UN,       7305 non-null int32
UNH,      7305 non-null int32
EV24      7305 non-null object
YYYY      7305 non-null int32
MM        7305 non-null int32
DD        7305 non-null int32
dtypes: int32(30), object(13)
memory usage: 1.6+ MB

In [158]:
#counting = {}
#for value in df['STN,']:
#    counting[value] = counting.get(value, 0) + 1
#counting

In [159]:
#train and ev df
mask = df['YYYY']== 2019
test_df = df[mask]
ev_df  = df[~mask]

In [160]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression

# get x and y
x_train, y_train = train_df.drop('TG,', axis=1), train_df['TG,']
# split the data for initial testing
X_train, X_test, Y_train, Y_test = train_test_split(x_train, y_train, test_size=0.2,random_state=1)

In [161]:
reg = LinearRegression()
reg.fit(x_train, y_train)

TypeError: float() argument must be a string or a number, not 'Timestamp'